global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PRISM Services
  - job_name: 'prism-api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prism-data-ingestion'
    static_configs:
      - targets: ['data-ingestion:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prism-digital-twin'
    static_configs:
      - targets: ['digital-twin:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prism-ai-pipeline'
    static_configs:
      - targets: ['ai-pipeline:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prism-alert-management'
    static_configs:
      - targets: ['alert-management:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prism-user-management'
    static_configs:
      - targets: ['user-management:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Infrastructure
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgis'
    static_configs:
      - targets: ['postgis:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093